# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
  image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/

cache:
  paths:
    - .cache/pip

before_script:
  - python --version # For debugging
  - python -m pip install --upgrade pip
  - pip install -e .
  - pip install -r dev_requirements.txt

black:
  script:
    - black --check --diff .

isort:
  script:
    - isort --check-only --diff .

style:
  script:
    - flake8

test:
  script:
    - pytest --cov --cov-fail-under=100 -Wd

typing:
  script:
    - mypy
