# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
  image: python:3.8

stages:
  - pre-commit
  # - test
  - build-push
  - push

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REGISTRY_URL: "9ygszqk0.gra7.container-registry.ovh.net"
  DOCKER_IMAGE: "$REGISTRY_URL/pulser-myqlm/pulser-myqlm"
  DOCKER_TAG: "$CI_COMMIT_REF_SLUG"
  DOCKER_TAG_SANITIZED: "${CI_COMMIT_REF_NAME//\//-}" # Sanitize the branch name

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/

cache:
  paths:
    - .cache/pip

before_script:
  - python --version # For debugging
  - python -m pip install --upgrade pip
  - pip install -e .
  - pip install -r dev_requirements.txt

black:
  stage: pre-commit
  script:
    - black --check --diff .

isort:
  stage: pre-commit
  script:
    - isort --check-only --diff .

style:
  stage: pre-commit
  script:
    - flake8

typing:
  stage: pre-commit
  script:
    - mypy

# test:
#   stage: test
#   script:
#     - pytest --cov --cov-fail-under=100 ./tests

build_and_push:
  stage: build-push
  interruptible: false
  image: ${REGISTRY_URL}/public/docker:cli
  before_script:
    - until docker info; do sleep 1; done
    - echo $HARBOR_API_PWD  | docker login -u $HARBOR_API_USER $REGISTRY_URL --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG_SANITIZED -f ./containerized/pulser_myqlm.Dockerfile .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG_SANITIZED
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
        docker tag $DOCKER_IMAGE:$DOCKER_TAG_SANITIZED $DOCKER_IMAGE:latest
        docker push $DOCKER_IMAGE:latest
      fi
